<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'user_id' => 2,
                'name_last' => 'Admin',
                'name_first' => 'System',
                'name_middle' => null,
                'domain_email' => 'admin@gordoncollege.edu.ph',
                'password' => Hash::make('admin123'), // Secure default password
                'role' => 'HR',
                'department_id' => null,
                'current_rank' => null,
                'current_salary' => null,
                'nature_of_appointment' => null,
                'educational_attainment' => null,
                'eligibility_exams' => null,
                'teaching_experience_years' => 0,
                'industry_experience_years' => 0,
                'applying_for' => null,
                'date_of_last_promotion' => null,
                'status' => 'inactive',
                'is_first_login' => false,
                'doctorate' => json_encode([]),
                'educational_attainment_json' => json_encode([]),
                'eligibility_exams_json' => json_encode([]),
                'applying_for_json' => json_encode([]),
                'created_at' => '2026-04-09 08:11:18',
                'updated_at' => '2026-04-09 08:11:18',
            ],
            [
                'user_id' => 3,
                'name_last' => 'VPAA',
                'name_first' => 'System',
                'name_middle' => null,
                'domain_email' => 'vpaa@gordoncollege.edu.ph',
                'password' => Hash::make('admin123'),
                'role' => 'VPAA',
                'department_id' => null,
                'current_rank' => null,
                'current_salary' => null,
                'nature_of_appointment' => null,
                'educational_attainment' => null,
                'eligibility_exams' => null,
                'teaching_experience_years' => 0,
                'industry_experience_years' => 0,
                'applying_for' => null,
                'date_of_last_promotion' => null,
                'status' => 'inactive',
                'is_first_login' => false,
                'doctorate' => json_encode([]),
                'educational_attainment_json' => json_encode([]),
                'eligibility_exams_json' => json_encode([]),
                'applying_for_json' => json_encode([]),
                'created_at' => '2026-04-11 09:06:25',
                'updated_at' => '2026-04-11 09:06:25',
            ],
            [
                'user_id' => 16,
                'name_last' => 'Sancon',
                'name_first' => 'John Carlos',
                'name_middle' => null,
                'domain_email' => 'faculty@gordoncollege.edu.ph',
                'password' => Hash::make('admin123'),
                'role' => 'Faculty',
                'department_id' => 1,
                'current_rank' => 'Instructor III',
                'current_salary' => null,
                'nature_of_appointment' => 'Full-Time',
                'educational_attainment' => 'Bachelor of Science in Computer Science',
                'eligibility_exams' => 'Civil Service Professional — Passed May 2026',
                'teaching_experience_years' => 8,
                'industry_experience_years' => 4,
                'applying_for' => 'Assistant Professor I, Assistant Professor II, Assistant Professor III',
                'date_of_last_promotion' => null,
                'status' => 'ranking',
                'is_first_login' => false,
                'doctorate' => json_encode([['degree' => 'Doctor of Philosophy in Science', 'pending' => false, 'institution' => 'Gordon College · 2014', 'yearGraduated' => null]]),
                'educational_attainment_json' => json_encode([['level' => "Bachelor's", 'degree' => 'Bachelor of Science in Computer Science', 'pending' => false, 'institution' => 'Gordon College · 2013', 'yearGraduated' => null]]),
                'eligibility_exams_json' => json_encode([['text' => 'Civil Service Professional — Passed May 2026', 'pending' => false, 'examName' => 'Civil Service Professional — Passed May 2026', 'datePassed' => null]]),
                'applying_for_json' => json_encode(["Assistant Professor I", "Assistant Professor II", "Assistant Professor III"]),
                'created_at' => '2026-05-02 09:59:09',
                'updated_at' => '2026-05-02 09:59:09',
            ],
            [
                'user_id' => 17,
                'name_last' => 'Sancon',
                'name_first' => 'John Doe',
                'name_middle' => null,
                'domain_email' => 'sancon.doe@gordoncollege.edu.ph',
                'password' => Hash::make('admin123'),
                'role' => 'Faculty',
                'department_id' => 8,
                'current_rank' => 'Instructor II',
                'current_salary' => null,
                'nature_of_appointment' => 'Permanent',
                'educational_attainment' => null,
                'eligibility_exams' => null,
                'teaching_experience_years' => null,
                'industry_experience_years' => null,
                'applying_for' => null,
                'date_of_last_promotion' => null,
                'status' => 'inactive',
                'is_first_login' => true,
                'doctorate' => json_encode([]),
                'educational_attainment_json' => json_encode([]),
                'eligibility_exams_json' => json_encode([]),
                'applying_for_json' => json_encode([]),
                'created_at' => '2026-05-05 14:41:10',
                'updated_at' => '2026-05-05 14:41:10',
            ],
            [
                'user_id' => 20,
                'name_last' => 'Quilitorio',
                'name_first' => 'Juan Christ',
                'name_middle' => null,
                'domain_email' => 'faculty2@gordoncollege.edu.ph',
                'password' => Hash::make('admin123'),
                'role' => 'Faculty',
                'department_id' => 7,
                'current_rank' => 'Instructor I',
                'current_salary' => null,
                'nature_of_appointment' => 'Permanent',
                'educational_attainment' => 'Bachelor of Education, Arts, and Science',
                'eligibility_exams' => null,
                'teaching_experience_years' => null,
                'industry_experience_years' => null,
                'applying_for' => 'Instructor I, Instructor III, Instructor II',
                'date_of_last_promotion' => null,
                'status' => 'inactive',
                'is_first_login' => false,
                'doctorate' => json_encode([]),
                'educational_attainment_json' => json_encode([['level' => "Bachelor's", 'degree' => 'Bachelor of Education, Arts, and Science', 'pending' => false, 'institution' => 'Gordon College · 2014', 'yearGraduated' => null]]),
                'eligibility_exams_json' => json_encode([]),
                'applying_for_json' => json_encode(["Instructor I", "Instructor III", "Instructor II"]),
                'created_at' => '2026-05-07 13:21:55',
                'updated_at' => '2026-05-07 13:21:55',
            ],
            [
                'user_id' => 21,
                'name_last' => 'Reyes',
                'name_first' => 'Jian Carlo',
                'name_middle' => null,
                'domain_email' => 'faculty3@gordoncollege.edu.ph',
                'password' => Hash::make('admin123'),
                'role' => 'Faculty',
                'department_id' => 1,
                'current_rank' => 'Instructor I',
                'current_salary' => null,
                'nature_of_appointment' => 'Permanent',
                'educational_attainment' => null,
                'eligibility_exams' => null,
                'teaching_experience_years' => 0,
                'industry_experience_years' => 0,
                'applying_for' => null,
                'date_of_last_promotion' => null,
                'status' => 'inactive',
                'is_first_login' => true,
                'doctorate' => null,
                'educational_attainment_json' => null,
                'eligibility_exams_json' => null,
                'applying_for_json' => null,
                'created_at' => '2026-05-07 13:36:17',
                'updated_at' => '2026-05-07 13:36:17',
            ]
        ];

        DB::table('users')->insert($users);
    }
}